# Generated by Django 3.2 on 2021-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20210503_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'publish'), ('DR', 'draft')], default='DR', max_length=2),
        ),
    ]
